// ─────────────────────────────────────────────────────────────────────────
// Fortress root public key — v1.1.5 Phase 1.5 (Guardian Core Axis 2)
// ─────────────────────────────────────────────────────────────────────────
//
// The Ed25519 root public key of the WMA Fortress signing hierarchy.
// All cloud-supplied policies are signed by a signing key, which is itself
// signed by this root. The verifier in src/shield/signature.js chains
// from policy → signing_key → ROOT to decide whether to trust a policy.
//
// The root PRIVATE key NEVER touches this file (nor any customer machine,
// nor any release artifact). It lives in the Fortress operator's offline
// vault. Only the public counterpart is shipped, and only its public
// counterpart is needed to verify.
//
// ROTATION POLICY:
//   - Compromised root → ship a new SDK version with both the old AND new
//     root keys in an array, give customers a grace window to upgrade,
//     then ship another SDK version with only the new key. This is the
//     same "double-signing" model used by Sigstore + Let's Encrypt.
//   - Routine rotation: every 2 years. Signing keys (one tier down) are
//     rotated every quarter and don't require an SDK release.
//
// ─────────────────────────────────────────────────────────────────────────
// PLACEHOLDER WARNING
// ─────────────────────────────────────────────────────────────────────────
//
// The value below is a PLACEHOLDER, not a real Fortress root key. It was
// generated by a one-shot script for development purposes and the private
// counterpart is publicly known (it's in git history). DO NOT publish a
// release that still contains this placeholder.
//
// Before publishing v1.1.5 to npm:
//   1. The Fortress operator generates a new keypair offline:
//        node -e "
//          const {generateKeyPairSync} = require('node:crypto');
//          const k = generateKeyPairSync('ed25519');
//          console.log('public:', k.publicKey.export({format:'der',type:'spki'}).slice(-32).toString('base64'));
//          console.log('private (KEEP SECRET):', k.privateKey.export({format:'pem',type:'pkcs8'}));
//        "
//   2. Store the private key in the Fortress secrets vault. It must be
//      able to sign the FIRST signing key for the very first policy push.
//   3. Replace WMA_FORTRESS_ROOT_PUBKEY_B64 below with the public output.
//   4. Bump v1.1.5, run the suite, push, tag, npm publish.
//
// Failing to replace this placeholder before release would mean ANY entity
// that has the placeholder private key could sign signing-keys that the
// SDK trusts. Loud comments + a runtime "I'm a placeholder" warning are
// here to prevent that. See src/shield/signature.js for the verifier
// itself — it has no knowledge of which root is the real one, it just
// trusts whatever this file exports.
//
// ─────────────────────────────────────────────────────────────────────────

// DO NOT USE — placeholder only. Replace before release.
// 32-byte Ed25519 public key as base64 (44 chars).
export const WMA_FORTRESS_ROOT_PUBKEY_B64 = 'PLACEHOLDER_REPLACE_BEFORE_PUBLISH_AAAAAAAA==';

// Set to `true` while the placeholder above is in place. The runtime
// can then surface a clear "you're trusting a known-compromised dev key"
// warning instead of silently chaining to a public-private-key pair.
export const WMA_FORTRESS_ROOT_IS_PLACEHOLDER = true;
