// ─────────────────────────────────────────────────────────────────────────
// Fortress root public key — v1.1.5 Phase 1.5 (Guardian Core Axis 2)
// ─────────────────────────────────────────────────────────────────────────
//
// The Ed25519 root public key of the WMA Fortress signing hierarchy.
// All cloud-supplied policies are signed by a signing key, which is itself
// signed by this root. The verifier in src/shield/signature.js chains
// from policy → signing_key → ROOT to decide whether to trust a policy.
//
// The root PRIVATE key NEVER touches this file (nor any customer machine,
// nor any release artifact). It lives in the Fortress operator's offline
// vault. Only the public counterpart is shipped, and only its public
// counterpart is needed to verify.
//
// ROTATION POLICY:
//   - Compromised root → ship a new SDK version with both the old AND new
//     root keys in an array, give customers a grace window to upgrade,
//     then ship another SDK version with only the new key. This is the
//     same "double-signing" model used by Sigstore + Let's Encrypt.
//   - Routine rotation: every 2 years. Signing keys (one tier down) are
//     rotated every quarter and don't require an SDK release.
//
// ─────────────────────────────────────────────────────────────────────────
// Real root pubkey — generated by offline ceremony on 2026-06-02
// ─────────────────────────────────────────────────────────────────────────
//
// The private counterpart NEVER touched this repository, npm, GitHub, or
// any connected machine. It was generated on the operator's machine in
// an air-gapped session and immediately stored in 1Password Vault under
// "WMA Fortress Root Private Key v1". It will be used 4× per year to
// sign new signing keys for the Fortress signing pipeline.
//
// Fortress operator: Minedor (arma@talkytranslate.com)
//
// To rotate this key (every 2 years routine, or on suspected compromise):
//   1. Generate a NEW keypair offline (same node:crypto snippet)
//   2. Ship an SDK version with BOTH old + new pubkeys in an array,
//      give customers 6-12 months overlap
//   3. Ship a follow-up SDK version with only the new pubkey
//
// 32-byte Ed25519 public key as base64 (44 chars).
export const WMA_FORTRESS_ROOT_PUBKEY_B64 = 'w4qKFACBbawZW1kx2wWxnITlOfvLDe+SXaPyZvp+mV4=';

// Flipped to false at release time (v1.1.5). The FortressPolicySource
// reads this to decide whether to skip verification entirely (placeholder
// era) or strictly enforce the chain (production). Keep this field —
// future rotations may temporarily re-enable placeholder mode in
// release-candidate builds where the new root isn't yet provisioned.
export const WMA_FORTRESS_ROOT_IS_PLACEHOLDER = false;
