#!/usr/bin/env node
// wma-service — install WatchMyAgents as an always-on OS background service.
//
// Turns the manual `wma-fetch --watch` (and optionally `wma-shield`) commands
// into OS-native services that start at login, restart on crash, and run with
// NO terminal — so the WGS loop is truly automatic on the customer's machine.
//
//   macOS  → launchd LaunchAgent (~/Library/LaunchAgents)
//   Linux  → systemd user unit   (~/.config/systemd/user)
//
// One integrated install:
//   wma-service install --agent-id agent_xxx [--interval 5m] [--with-shield]
//   wma-service status
//   wma-service uninstall [--with-shield]
//
// Secrets NEVER go in the plist/unit. They're snapshotted (from the current
// environment) into a protected env file (~/.watchmyagents/env, chmod 600) that
// the service loads at runtime. Required env at install time:
//   ANTHROPIC_API_KEY, WMA_API_KEY, WMA_FORTRESS_BASE_URL, WMA_SIGNALS_SALT
// Raw logs stay local (Containment); only anonymized signals are uploaded.

import os from 'node:os';
import { mkdirSync, writeFileSync, rmSync, existsSync, chmodSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { isValidAgentId } from '../src/validate.js';
import { maybePrintVersionAndExit } from '../src/version.js';

const HOME = os.homedir();
const PLATFORM = process.platform;                       // 'darwin' | 'linux' | …
const UID = typeof process.getuid === 'function' ? process.getuid() : null;
const NODE = process.execPath;                            // absolute node binary
const FETCH_SCRIPT = fileURLToPath(new URL('./fetch-anthropic.js', import.meta.url));
const SHIELD_SCRIPT = fileURLToPath(new URL('./shield.js', import.meta.url));

const CONFIG_DIR = join(HOME, '.watchmyagents');
const ENV_FILE = join(CONFIG_DIR, 'env');
const LOG_DIR_DEFAULT = join(CONFIG_DIR, 'logs');

const REQUIRED_ENV = ['ANTHROPIC_API_KEY', 'WMA_API_KEY', 'WMA_FORTRESS_BASE_URL', 'WMA_SIGNALS_SALT'];

const WATCH_LABEL = 'com.watchmyagents.watch';
const SHIELD_LABEL = 'com.watchmyagents.shield';

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const k = a.slice(2);
      const n = argv[i + 1];
      if (n == null || n.startsWith('--')) out[k] = true;
      else { out[k] = n; i++; }
    } else out._.push(a);
  }
  return out;
}

function die(msg, code = 1) { process.stderr.write(`error: ${msg}\n`); process.exit(code); }
function info(msg) { process.stdout.write(`[wma-service] ${msg}\n`); }
function warn(msg) { process.stderr.write(`[wma-service] ⚠️  ${msg}\n`); }

function sh(value) { return `"${String(value).replace(/(["$`\\])/g, '\\$1')}"`; }

// ── Config (secrets) ──────────────────────────────────────────────────────
function writeEnvFile() {
  const missing = REQUIRED_ENV.filter((k) => !process.env[k]);
  if (missing.length) {
    die(`missing required env var(s): ${missing.join(', ')}\n` +
        '       Export them in this shell, then re-run install. e.g.:\n' +
        '         export $(grep -v "^#" .env | xargs)\n' +
        '         export WMA_API_KEY=... WMA_FORTRESS_BASE_URL=... WMA_SIGNALS_SALT=...');
  }
  // The env file is sourced by the launcher (set -a; . file) and read by
  // systemd's EnvironmentFile. A newline in a value would inject extra lines /
  // corrupt the file, so reject it. (Our value types — hex salt, wma_/sk-ant
  // keys, https URL — never legitimately contain newlines.)
  for (const k of REQUIRED_ENV) {
    if (/[\r\n]/.test(process.env[k])) die(`${k} contains a newline — refusing to write it to the env file`);
  }
  mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  // Plain KEY=value lines — readable by both `set -a; . file` (launchd launcher)
  // and systemd's EnvironmentFile=. No quoting needed (no spaces in our values).
  const body = REQUIRED_ENV.map((k) => `${k}=${process.env[k]}`).join('\n') + '\n';
  writeFileSync(ENV_FILE, body, { mode: 0o600 });
  chmodSync(ENV_FILE, 0o600);
  info(`secrets written to ${ENV_FILE} (chmod 600)`);
}

// ── macOS (launchd) ─────────────────────────────────────────────────────--
function launchAgentsDir() { return join(HOME, 'Library', 'LaunchAgents'); }
function plistPath(label) { return join(launchAgentsDir(), `${label}.plist`); }
function launcherPath(label) { return join(CONFIG_DIR, `${label}.launcher.sh`); }

function writeLauncher(label, scriptPath, args) {
  const argLine = args.map(sh).join(' ');
  // Load secrets with a read-loop, NOT '. file' / source. Sourcing would
  // shell-evaluate each value, so a secret like FOO=https://x/$(cmd) would
  // execute cmd at launch. A read-loop assigns the value literally — the
  // content is never re-scanned for command substitution.
  const body = `#!/bin/sh
# Generated by wma-service. Loads secrets WITHOUT shell-evaluating their values.
while IFS='=' read -r __k __v; do
  [ -n "$__k" ] && export "$__k=$__v"
done < ${sh(ENV_FILE)}
exec ${sh(NODE)} ${sh(scriptPath)} ${argLine}
`;
  const p = launcherPath(label);
  writeFileSync(p, body, { mode: 0o700 });
  chmodSync(p, 0o700);
  return p;
}

function writePlist(label, launcher) {
  const outLog = join(CONFIG_DIR, `${label}.out.log`);
  const errLog = join(CONFIG_DIR, `${label}.err.log`);
  // Pre-create the log files 0600 so launchd appends to owner-only files.
  // (No secrets are logged, but defense-in-depth on world-readable home files.)
  for (const lp of [outLog, errLog]) {
    if (!existsSync(lp)) writeFileSync(lp, '', { mode: 0o600 });
    else chmodSync(lp, 0o600);
  }
  const body = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array><string>${launcher}</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ProcessType</key><string>Background</string>
  <key>StandardOutPath</key><string>${outLog}</string>
  <key>StandardErrorPath</key><string>${errLog}</string>
</dict>
</plist>
`;
  mkdirSync(launchAgentsDir(), { recursive: true });
  const p = plistPath(label);
  writeFileSync(p, body, { mode: 0o644 });
  return p;
}

function launchctl(args, { ignoreError = false } = {}) {
  try {
    execFileSync('launchctl', args, { stdio: 'pipe' });
    return true;
  } catch (e) {
    if (!ignoreError) warn(`launchctl ${args.join(' ')} failed: ${(e.stderr || e.message).toString().trim().slice(0, 200)}`);
    return false;
  }
}

// Synchronous sleep (installer CLI — blocking is fine). Used to let launchd's
// asynchronous bootout finish before we bootstrap again.
function syncSleep(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}
function macLoaded(label) {
  try { execFileSync('launchctl', ['print', `gui/${UID}/${label}`], { stdio: 'pipe' }); return true; }
  catch { return false; }
}

function macLoad(label, plist) {
  const domain = `gui/${UID}`;
  // bootout is async: on reinstall, bootstrapping again before the old instance
  // is gone races and silently fails (symptom: reinstall = dead services).
  // Wait for the prior instance to disappear, then retry bootstrap.
  if (macLoaded(label)) {
    launchctl(['bootout', `${domain}/${label}`], { ignoreError: true });
    for (let i = 0; i < 20 && macLoaded(label); i++) syncSleep(150);
  }
  let ok = false;
  for (let attempt = 0; attempt < 5 && !ok; attempt++) {
    ok = launchctl(['bootstrap', domain, plist], { ignoreError: attempt < 4 });
    if (!ok) syncSleep(250);
  }
  launchctl(['enable', `${domain}/${label}`], { ignoreError: true });
  if (ok) info(`loaded ${label} (launchd) — running now + at every login`);
  else {
    warn(`could not auto-load ${label}. Load it manually:`);
    process.stdout.write(`  launchctl bootout gui/${UID}/${label} 2>/dev/null; launchctl bootstrap gui/${UID} ${plist}\n`);
  }
}

function macUnload(label) {
  const domain = `gui/${UID}`;
  launchctl(['bootout', `${domain}/${label}`], { ignoreError: true });
  for (const p of [plistPath(label), launcherPath(label)]) if (existsSync(p)) rmSync(p);
  info(`removed ${label} (launchd)`);
}

function macInstallOne(label, scriptPath, args) {
  const launcher = writeLauncher(label, scriptPath, args);
  const plist = writePlist(label, launcher);
  macLoad(label, plist);
}

// ── Linux (systemd user) ───────────────────────────────────────────────────
function systemdDir() { return join(HOME, '.config', 'systemd', 'user'); }
function unitName(label) { return `${label.replace(/\./g, '-')}.service`; }
function unitPath(label) { return join(systemdDir(), unitName(label)); }

function writeUnit(label, desc, scriptPath, args) {
  // Quote every token for systemd. systemd splits ExecStart on whitespace and
  // does NOT run a shell; double-quotes group tokens and honor \" and \\.
  const sdQuote = (s) => `"${String(s).replace(/(["\\])/g, '\\$1')}"`;
  const exec = [NODE, scriptPath, ...args].map(sdQuote).join(' ');
  const body = `[Unit]
Description=${desc}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${ENV_FILE}
ExecStart=${exec}
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
`;
  mkdirSync(systemdDir(), { recursive: true });
  const p = unitPath(label);
  writeFileSync(p, body, { mode: 0o644 });
  return p;
}

function systemctl(args, { ignoreError = false } = {}) {
  try { execFileSync('systemctl', ['--user', ...args], { stdio: 'pipe' }); return true; }
  catch (e) { if (!ignoreError) warn(`systemctl --user ${args.join(' ')} failed: ${(e.stderr || e.message).toString().trim().slice(0, 200)}`); return false; }
}

function linuxInstallOne(label, desc, scriptPath, args) {
  writeUnit(label, desc, scriptPath, args);
  const unit = unitName(label);
  systemctl(['daemon-reload'], { ignoreError: true });
  const ok = systemctl(['enable', '--now', unit]);
  if (ok) info(`enabled ${unit} (systemd) — running now + at login. For boot-without-login: loginctl enable-linger ${process.env.USER || ''}`);
  else { warn(`could not auto-enable ${unit}. Enable manually:`); process.stdout.write(`  systemctl --user enable --now ${unit}\n`); }
}

function linuxUninstallOne(label) {
  const unit = unitName(label);
  systemctl(['disable', '--now', unit], { ignoreError: true });
  if (existsSync(unitPath(label))) rmSync(unitPath(label));
  systemctl(['daemon-reload'], { ignoreError: true });
  info(`removed ${unit} (systemd)`);
}

// ── Commands ────────────────────────────────────────────────────────────--
function cmdInstall(args) {
  const allAgents = !!args['all-agents'];
  const agentId = args['agent-id'];
  if (!allAgents && !agentId) die('--agent-id required (or --all-agents to cover the whole fleet)');
  if (agentId && !isValidAgentId(agentId)) die(`--agent-id invalid format (expected "agent_" + alphanumeric, got "${agentId}")`);
  const interval = args.interval || '5m';
  if (!/^\d+[smhd]$/.test(interval)) die(`--interval invalid format (expected like 30s, 5m, 1h, 2d; got "${interval}")`);
  const logDir = args['log-dir'] || LOG_DIR_DEFAULT;
  const withShield = !!args['with-shield'];

  if (PLATFORM !== 'darwin' && PLATFORM !== 'linux') {
    die(`unsupported platform "${PLATFORM}". Supported: macOS (launchd), Linux (systemd).\n` +
        '       Run the daemon manually or wrap it in your own process manager:\n' +
        `         wma-fetch ${allAgents ? '--all-agents' : `--agent-id ${agentId}`} --watch --upload --interval ${interval}`);
  }

  mkdirSync(logDir, { recursive: true, mode: 0o700 });
  writeEnvFile();

  const target = allAgents ? ['--all-agents'] : ['--agent-id', agentId];
  const watchArgs = [...target, '--watch', '--upload', '--interval', interval, '--log-dir', logDir];
  const shieldArgs = [...target, '--policies-source', 'fortress', '--log-dir', logDir];

  if (PLATFORM === 'darwin') {
    macInstallOne(WATCH_LABEL, FETCH_SCRIPT, watchArgs);
    if (withShield) macInstallOne(SHIELD_LABEL, SHIELD_SCRIPT, shieldArgs);
  } else {
    linuxInstallOne(WATCH_LABEL, 'WatchMyAgents Watch daemon', FETCH_SCRIPT, watchArgs);
    if (withShield) linuxInstallOne(SHIELD_LABEL, 'WatchMyAgents Shield enforcement', SHIELD_SCRIPT, shieldArgs);
  }

  info('done — the WGS loop now runs always-on, no terminal needed.');
  info(`logs: ${CONFIG_DIR}/*.log  |  captured events: ${logDir}`);
  info(`status:  wma-service status    uninstall:  wma-service uninstall${withShield ? ' --with-shield' : ''}`);
}

function cmdUninstall(args) {
  const withShield = !!args['with-shield'];
  if (PLATFORM === 'darwin') {
    macUnload(WATCH_LABEL);
    if (withShield) macUnload(SHIELD_LABEL);
  } else if (PLATFORM === 'linux') {
    linuxUninstallOne(WATCH_LABEL);
    if (withShield) linuxUninstallOne(SHIELD_LABEL);
  } else {
    die(`unsupported platform "${PLATFORM}"`);
  }
  info('uninstalled. (Secrets in ' + ENV_FILE + ' left intact — delete manually if you want them gone.)');
}

function cmdStatus() {
  if (PLATFORM === 'darwin') {
    try {
      const out = execFileSync('launchctl', ['list'], { encoding: 'utf8' });
      const lines = out.split('\n').filter((l) => l.includes('watchmyagents'));
      process.stdout.write(lines.length ? lines.join('\n') + '\n' : 'no WatchMyAgents services loaded\n');
    } catch { warn('could not query launchctl'); }
  } else if (PLATFORM === 'linux') {
    for (const label of [WATCH_LABEL, SHIELD_LABEL]) {
      try {
        const out = execFileSync('systemctl', ['--user', 'is-active', unitName(label)], { encoding: 'utf8' }).trim();
        process.stdout.write(`${unitName(label)}: ${out}\n`);
      } catch (e) {
        process.stdout.write(`${unitName(label)}: ${(e.stdout || 'inactive').toString().trim()}\n`);
      }
    }
  } else {
    die(`unsupported platform "${PLATFORM}"`);
  }
}

function usage() {
  process.stdout.write(`wma-service — run WatchMyAgents as an always-on OS service

Usage:
  wma-service install --agent-id agent_xxx [--interval 5m] [--log-dir DIR] [--with-shield]
  wma-service status
  wma-service uninstall [--with-shield]

Required env at install (snapshotted to ~/.watchmyagents/env, chmod 600):
  ANTHROPIC_API_KEY, WMA_API_KEY, WMA_FORTRESS_BASE_URL, WMA_SIGNALS_SALT

macOS → launchd LaunchAgent · Linux → systemd user unit.
The service starts at login and restarts on crash. Raw logs stay local.
`);
}

function main() {
  // v1.1.1 F-13: --version / -v short-circuit before any other parsing.
  maybePrintVersionAndExit(process.argv);
  const args = parseArgs(process.argv.slice(2));
  const cmd = args._[0];
  switch (cmd) {
    case 'install': return cmdInstall(args);
    case 'uninstall': return cmdUninstall(args);
    case 'status': return cmdStatus();
    default: usage(); process.exit(cmd ? 1 : 0);
  }
}

main();
